name: ggl

packages:
  - codegen/**
  - '*'
  - examples/**
  - ggl_pedantic/**
  - links/**

# Generated output of flutter_localizations
ignore:
  - synthetic_package

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  genfiles:
    run: |
      melos exec -c 1 -- \
        "flutter pub run build_runner build --delete-conflicting-outputs"
  lint:all:
    run: melos run analyze
    description: Run all static analysis checks.

  analyze:
    # We are setting the concurrency to 1 because a higher concurrency can crash
    # the analysis server on low performance machines (like GitHub Actions).
    run: |
      melos exec -c 1 -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.
  
  test:all:
    run: |
      melos run test --no-select
    description: |
      Run all tests available.
  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test --no-pub"
    description: Run `flutter test` for a specific package.
    select-package:
      dir-exists:
        - test
      ignore:
        - '*web*'
        - '*odm*'
        - '*example*'

  qualitycheck:
    run: |
      melos run clean:deep && \
      melos clean && \
      melos bootstrap && \
      melos run lint:all && \
      melos run build:all && \
      melos run test:all
    description: Run all targets generally expected in CI for a full local quality check.

  clean:deep:
    run: git clean -x -d -f -q
    description: Clean things very deeply, can be used to establish "pristine checkout" status.

  postclean: >
    melos exec -c 6 -- "flutter clean"