name: gql_code_builder
version: 0.5.1
description: Dart code builders taking *.graphql documents and SDL to build useful classes.
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  analyzer: '>=4.3.0'
  built_collection: ^5.0.0
  built_value: ^8.4.0
  code_builder: ^4.0.0
  collection: ^1.15.0
  gql: ^0.13.0
  gql_exec: ^0.4.0
  path: ^1.8.0
dev_dependencies: 
  build_runner: ^2.2.0
  gql_pedantic: ^2.0.0
  test: ^1.21.4
